# Generated by Django 5.0.4 on 2024-04-14 06:56

import django.db.models.deletion
import view.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0002_auto_20240413_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=view.models.getFileName)),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False, help_text='0-show,1-Hidden')),
            ],
        ),
        migrations.CreateModel(
            name='places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=view.models.getFileName)),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False, help_text='0-show,1-Hidden')),
                ('collections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='view.collection')),
            ],
        ),
        migrations.DeleteModel(
            name='POV',
        ),
    ]
