# Generated by Django 5.0.4 on 2024-04-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0004_collection_created_at_collection_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
